FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:44fd8f88f3b6463cda15571260f9ca3a0b78d3c8c8827a338e04ab3a23581a88 as build-env
ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
WORKDIR $APP_ROOT/src/

ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download

ADD ./cmd/ $APP_ROOT/src/cmd/
ADD ./pkg/ $APP_ROOT/src/pkg/
ADD ./Build.mak $APP_ROOT/src/Build.mak

RUN make -f Build.mak fetch-tsa-certs-linux-arm64 && \
    gzip fetch_tsa_certs_darwin_arm64 && \
    gzip fetch_tsa_certs_darwin_amd64 && \
    gzip fetch_tsa_certs_linux_amd64 && \
    gzip fetch_tsa_certs_linux_arm64 && \
    gzip fetch_tsa_certs_linux_ppc64le && \
    gzip fetch_tsa_certs_linux_s390x && \
    gzip fetch_tsa_certs_windows_amd64.exe


FROM scratch

ENV APP_ROOT=/opt/app-root

COPY LICENSE /licenses/license.txt
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_darwin_arm64.gz /fetch_tsa_certs_darwin_arm64.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_darwin_amd64.gz /fetch_tsa_certs_darwin_amd64.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_linux_amd64.gz /fetch_tsa_certs_linux_amd64.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_linux_arm64.gz /fetch_tsa_certs_linux_arm64.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_linux_ppc64le.gz /fetch_tsa_certs_linux_ppc64le.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_linux_s390x.gz /fetch_tsa_certs_linux_s390x.gz
COPY --from=build-env $APP_ROOT/src/fetch_tsa_certs_windows_amd64.exe.gz /fetch_tsa_certs_windows_amd64.exe.gz
