FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23@sha256:44fd8f88f3b6463cda15571260f9ca3a0b78d3c8c8827a338e04ab3a23581a88 as build-env
ARG TARGETOS
ARG TARGETARCH

ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
WORKDIR $APP_ROOT/src/

ADD go.mod go.sum $APP_ROOT/src/
RUN go mod download

ADD ./cmd/ $APP_ROOT/src/cmd/
ADD ./pkg/ $APP_ROOT/src/pkg/
ADD ./Build.mak $APP_ROOT/src/Build.mak

RUN make -f Build.mak fetch-tsa-certs-${TARGETOS}-${TARGETARCH}


FROM registry.access.redhat.com/ubi9-minimal:latest
ARG TARGETOS
ARG TARGETARCH

LABEL description="The fetch_tsa_certs binary is a cli used to configure the kms and tink signer types for Timestamp Authority."
LABEL io.k8s.description="The fetch_tsa_certs binary is a cli used to configure the kms and tink signer types for Timestamp Authority."
LABEL io.k8s.display-name="Fetch TSA certs container image for Red Hat Trusted Signer."
LABEL io.openshift.tags="fetch_tsa_certs"
LABEL summary="Provides the fetch_tsa_certs CLI binary."
LABEL com.redhat.component="fetch_tsa_certs"
LABEL name="fetch_tsa_certs"

COPY LICENSE /licenses/license.txt
COPY --from=build-env /opt/app-root/src/fetch_tsa_certs_${TARGETOS}_${TARGETARCH} /usr/local/bin/fetch_tsa_certs

USER 65532:65532

ENTRYPOINT ["fetch_tsa_certs"]
